version: '3.3'
services:
  database:
    image: mysql:5.7
    volumes:
      - ./dbdata:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    networks:
      - ds
  dockerized:
    build: ./docker-springboot-mysql
    networks:
      - ds
    depends_on:
     - database
    ports:
      - "8081:8081"
    environment:
      - MYSQL_HOST=database
      - MYSQL_PORT=3306
    env_file:
      - ./.env
networks:
  ds:
    driver: bridge